---
- hosts: ldapserver
  become: true
  become_user: root
  tasks:
    - name: Installs slapd & ldap_server on the ubuntu server
      apt: 
        name: ['slapd', 'ldap-utils']
        update_cache: true
        state: present

    - name: Start and Enable slapd (LDAP deamon)
       service: 
         name: slapd 
         state: started 
         enabled: true
       become: true
       become_user: root

     - name: Generate ldap-admin password Hash
       shell: slappasswd -h {SHA} -s {{ admin_pass }} > {{ path_to_admin_pass_hash }}

     - name: backup the old-original password
       shell: grep -v olcRootPW {{ path_to_hdb_conf['src'] }} > {{  path_to_hdb_conf['src'] }}.temp

     - name: Add line password hash to the config file (hdb)
       shell: "cat {{ path_to_admin_pass_hash }} | xargs echo olcRootPW: >> {{ path_to_hdb_conf['src'] }}"

     - name: Update server configuration (via hdb)
       template:
         src: "{{ path_to_hdb_conf['src'] }}"
         dest: "{{ path_to_hdb_conf['dest'] }}"

     - name: Update server monitor configuration
       template: 
         src: "{{ path_to_monitor_conf['src'] }}"
         dest: "{{ path_to_monitor_conf['dest'] }}"
